export type Category = "market" | "tech";

export type Author = {
  id: string;
  name: string;
  nameEn: string;
  role: string;
  roleEn: string;
  xHandle?: string | null;
};

export type Post = {
  slug: string;
  title: string;
  titleEn: string;
  excerpt: string;
  excerptEn: string;
  category: Category;
  date: string;
  dateEn: string;
  readTime: string;
  readTimeEn: string;
  authorId: string;
  tags: string[];
  image?: string;
  body: string[];
  bodyEn: string[];
  bullets: string[];
  bulletsEn: string[];
};

export type PostSummary = Omit<
  Post,
  "body" | "bullets" | "bodyEn" | "bulletsEn"
>;

export const CATEGORY_LABELS: Record<Category, string> = {
  market: "Market",
  tech: "Tech",
};

export const authors: Author[] = [
  {
    id: "beleken",
    name: "Андрей Белекпен",
    nameEn: "Andrey Beleken",
    role: "Инженерия и архитектура",
    roleEn: "Engineering & Architecture",
    xHandle: null,
  },
  {
    id: "israelyan",
    name: "Ерем Исраелян",
    nameEn: "Erem Israelyan",
    role: "Продукт и стратегии",
    roleEn: "Product & Strategy",
    xHandle: null,
  },
];

export const posts: Post[] = [
  {
    slug: "solana-kak-yavlenie",
    title: "Solana как явление: почему это больше, чем просто быстрый блокчейн",
    titleEn: "Solana as a phenomenon: why it's more than just a fast blockchain",
    excerpt:
      "Когда в индустрии говорят о Solana, чаще всего разговор сводится к скорости, дешевым транзакциям и техническим метрикам. Но если смотреть глубже, становится понятно: Solana — это не просто блокчейн, а отдельное явление внутри крипторынка.",
    excerptEn:
      "When people talk about Solana, the conversation usually narrows to speed, cheap transactions, and technical metrics. But look deeper and it becomes clear: Solana is not just a blockchain, it is a distinct phenomenon inside crypto.",
    category: "tech",
    date: "12 янв 2025",
    dateEn: "Jan 12, 2025",
    readTime: "9 мин",
    readTimeEn: "9 min",
    authorId: "beleken",
    tags: ["solana", "speed", "ux", "ecosystem", "infrastructure", "creators"],
    image: "/blog/solana-kak-yavlenie.jpg",
    body: [
      "Когда в индустрии говорят о Solana, чаще всего разговор сводится к скорости, дешевым транзакциям и техническим метрикам. Но если смотреть глубже, становится понятно: Solana — это не просто блокчейн, а отдельное явление внутри крипторынка, которое меняет логику того, как создаются продукты, кто их создает и почему они вообще возможны.",
      "Блокчейн как инфраструктура, а не идеология.",
      "Большинство ранних блокчейнов формировались вокруг идеологических установок: децентрализация любой ценой, максимальная устойчивость, минимальное доверие. Ethereum стал эталоном этой философии — гибкий, универсальный, но дорогой и медленный.",
      "Solana с самого начала пошла по другому пути. Здесь блокчейн — это инфраструктура, а не манифест. Вопрос ставился не «как быть максимально децентрализованными», а «как сделать систему, способную обслуживать миллионы пользователей без деградации UX».",
      "Именно поэтому Solana больше похожа на высоконагруженный backend, чем на классический криптопротокол.",
      "Скорость как фактор культуры.",
      "Solana часто называют «быстрым блокчейном», но скорость здесь — не просто технический параметр. Она формирует культуру.",
      "Когда транзакция стоит доли цента и подтверждается почти мгновенно: разработчики экспериментируют чаще, пользователи совершают больше действий, продукты можно запускать и итеративно дорабатывать в реальном времени.",
      "В такой среде появляются форматы, которые невозможны в медленных сетях: on-chain order books, высокочастотные стратегии, массовые consumer-приложения, мем-экономика с реальной ликвидностью.",
      "Solana создала условия, при которых блокчейн перестал быть узким горлышком.",
      "Экосистема, ориентированная на креаторов.",
      "Один из ключевых сдвигов, который принесла Solana, — это смещение фокуса с «протоколов» на креаторов: создателей токенов, разработчиков микропродуктов, комьюнити-лидеров, трейдеров и маркет-мейкеров.",
      "Низкий порог входа сделал возможным запуск токена, NFT-коллекции или продукта за часы, а не месяцы. Это привело к взрывному росту количества экспериментов — не все из них качественные, но именно из этого хаоса рождаются новые форматы.",
      "Solana — это среда, где скорость идеи важнее идеальной архитектуры.",
      "Не без проблем — и это важно.",
      "Важно честно признать: Solana не идеальна. Перегрузки сети, остановки валидаторов, вопросы к уровню децентрализации — всё это реальные проблемы, которые рынок не игнорирует.",
      "Но здесь возникает ключевой момент: Solana развивается как живой продукт, а не как застывший протокол. Ошибки признаются, архитектура пересобирается, приоритет — масштабирование под реальное использование, а не под теоретические модели.",
      "Это роднит Solana скорее с big tech-платформами, чем с академическими блокчейн-проектами.",
      "Почему Solana — это именно «явление».",
      "Solana стала катализатором сдвига: от DeFi для избранных → к массовым рынкам, от долгих релизов → к быстрой итерации, от идеологии → к продукту.",
      "Она показала, что блокчейн может быть быстрым, дешевым и удобным, не превращаясь при этом в централизованную базу данных — пусть и с компромиссами.",
      "Именно поэтому Solana так сильно влияет на всё, что происходит дальше: мем-рынки, prediction markets, копитрейдинг, creator-экономику.",
      "Это не просто сеть. Это платформа для экспериментов с будущей финансовой и цифровой реальностью.",
    ],
    bodyEn: [
      "When people in the industry talk about Solana, the conversation usually narrows to speed, cheap transactions, and technical metrics. But look deeper and it becomes clear: Solana is not just a blockchain, but a distinct phenomenon inside the crypto market that changes the logic of how products are built, who builds them, and why they are possible at all.",
      "Blockchain as infrastructure, not ideology.",
      "Most early blockchains formed around ideological principles: decentralization at any cost, maximum resilience, minimal trust. Ethereum became the reference for this philosophy — flexible and universal, but expensive and slow.",
      "Solana took a different path from the start. Here the blockchain is infrastructure, not a manifesto. The question was not \"how to be maximally decentralized,\" but \"how to build a system that can serve millions of users without UX degradation.\"",
      "That is why Solana looks more like a high-load backend than a classic crypto protocol.",
      "Speed as a cultural factor.",
      "Solana is often called a \"fast blockchain,\" but speed here is not just a technical metric. It shapes culture.",
      "When a transaction costs fractions of a cent and confirms almost instantly: developers experiment more, users perform more actions, products can launch and iterate in real time.",
      "In such an environment, formats that are impossible in slow networks appear: on-chain order books, high-frequency strategies, mass consumer apps, and meme economies with real liquidity.",
      "Solana created conditions where the blockchain stopped being a bottleneck.",
      "An ecosystem oriented around creators.",
      "One of the key shifts Solana brought is moving the focus from \"protocols\" to creators: token creators, micro-product developers, community leaders, traders, and market makers.",
      "A low entry barrier made it possible to launch a token, NFT collection, or product in hours rather than months. This led to an explosion of experiments — not all of them good, but new formats are born from this chaos.",
      "Solana is an environment where the speed of an idea matters more than perfect architecture.",
      "Not without problems — and that matters.",
      "It is important to admit honestly: Solana is not ideal. Network congestion, validator outages, and questions about decentralization are real issues the market does not ignore.",
      "But here is the key point: Solana evolves like a living product, not a frozen protocol. Errors are acknowledged, architecture is rebuilt, and the priority is scaling for real usage rather than theoretical models.",
      "This makes Solana closer to big tech platforms than to academic blockchain projects.",
      "Why Solana is exactly a \"phenomenon\".",
      "Solana became a catalyst for a shift: from DeFi for the few → to mass markets, from long releases → to fast iteration, from ideology → to product.",
      "It showed that a blockchain can be fast, cheap, and convenient without turning into a centralized database — albeit with trade-offs.",
      "That is why Solana influences everything that comes next: meme markets, prediction markets, copy trading, and the creator economy.",
      "This is not just a network. It is a platform for experiments with the future financial and digital reality.",
    ],
    bullets: [
      "Solana — это инфраструктура, а не идеологический манифест",
      "Скорость формирует культуру и открывает новые продуктовые форматы",
      "Фокус на креаторов запускает быстрые эксперименты и рост экосистемы",
    ],
    bulletsEn: [
      "Solana is infrastructure, not an ideological manifesto",
      "Speed shapes culture and unlocks new product formats",
      "A creator-first focus accelerates experiments and ecosystem growth",
    ],
  },
  {
    slug: "borba-za-skorost-v-solana",
    title: "Борьба за скорость в блокчейне Solana: почему миллисекунды решают всё",
    titleEn: "The speed race in Solana: why milliseconds decide everything",
    excerpt:
      "Скорость в блокчейне долгое время считалась второстепенным параметром, но по мере роста индустрии стало ясно: медленный блокчейн не может быть массовым.",
    excerptEn:
      "Speed was long considered secondary in blockchain, but as the industry grew it became clear: a slow blockchain cannot be mass-market.",
    category: "tech",
    date: "26 янв 2025",
    dateEn: "Jan 26, 2025",
    readTime: "9 мин",
    readTimeEn: "9 min",
    authorId: "beleken",
    tags: ["latency", "performance", "solana", "infrastructure"],
    image: "/blog/borba-za-skorost-v-solana.jpg",
    body: [
      "Скорость в блокчейне долгое время считалась второстепенным параметром. Важнее были безопасность, децентрализация, устойчивость к атакам. Но по мере того как криптоиндустрия начала выходить за рамки экспериментов, стало очевидно: медленный блокчейн не может быть массовым.",
      "Именно здесь Solana превратила скорость из «приятного бонуса» в ключевой принцип архитектуры.",
      "Почему скорость — это не просто TPS.",
      "Когда говорят о скорости блокчейна, чаще всего упоминают TPS — количество транзакций в секунду. Но в реальных продуктах пользователей волнует другое: время подтверждения, предсказуемость исполнения, отсутствие «зависаний» под нагрузкой.",
      "Solana изначально проектировалась не как цепочка редких и дорогих операций, а как система, способная обрабатывать поток событий — почти как биржевой движок или высоконагруженный API.",
      "По сути, Solana стремится быть не просто блокчейном, а реальным временем исполнения.",
      "Proof of History: фундамент гонки за миллисекундами.",
      "Ключевым техническим решением Solana стал Proof of History (PoH). Его суть проста, но радикальна: сеть заранее знает порядок событий, не тратя время на постоянное согласование между узлами.",
      "Это убирает один из самых дорогих элементов классических блокчейнов — синхронизацию времени и последовательности транзакций.",
      "В результате валидаторы работают быстрее, подтверждение блоков происходит стабильнее, система лучше масштабируется при росте нагрузки.",
      "PoH — это не про «больше TPS», а про меньше задержек на каждом этапе.",
      "Скорость как конкурентное оружие.",
      "Высокая скорость Solana стала не просто технологическим достижением, а рыночным фактором. Именно благодаря этому в экосистеме появились: on-chain order books, high-frequency стратегии, мгновенный copy trading, prediction-маркеты с живой ликвидностью, мем-рынки, где важна скорость входа и выхода.",
      "На медленных сетях такие продукты либо невозможны, либо превращаются в симуляцию с off-chain логикой.",
      "Solana показала, что UX в Web3 может быть сопоставим с Web2 — и это изменило ожидания пользователей.",
      "Обратная сторона скорости.",
      "Важно понимать: высокая скорость — это всегда компромиссы. Solana не раз сталкивалась с перегрузками сети, остановками валидаторов, проблемами при экстремальных пиках активности.",
      "Каждый такой инцидент моментально становился аргументом критиков. Но если смотреть стратегически, становится ясно: Solana выбрала путь сложной инженерии, а не безопасного минимализма.",
      "Она масштабируется не за счёт ограничения использования, а за счёт постоянного усложнения инфраструктуры.",
      "Firedancer и следующая стадия гонки.",
      "Пожалуй, самый важный сигнал зрелости Solana — появление альтернативных клиентских реализаций. Проект Firedancer, разрабатываемый Jump Crypto, — это попытка пересобрать валидатор Solana с нуля, сделав его быстрее, стабильнее, устойчивее к перегрузкам.",
      "Это принципиально важный момент: скорость перестаёт быть «фичей одного клиента» и становится системным свойством сети.",
      "Гонка за миллисекундами выходит на новый уровень.",
      "Почему эта борьба критична для будущего.",
      "Скорость в Solana — это не про рекорды и цифры в презентациях. Это про тип рынков, которые могут существовать: real-time трейдинг, массовые consumer-приложения, экономику креаторов, prediction markets с мгновенной реакцией на события.",
      "Чем быстрее сеть, тем меньше причин выносить логику off-chain. А значит — больше прозрачности, меньше доверия, больше реальной ончейн-экономики.",
      "Итог.",
      "Solana участвует не просто в гонке блокчейнов. Она участвует в гонке за право быть инфраструктурой реального времени.",
      "Да, это путь с рисками. Да, он требует сложных инженерных решений. Но именно этот путь открывает двери для новых рынков, которые раньше в блокчейне были невозможны.",
    ],
    bodyEn: [
      "Speed in blockchain was long considered a secondary parameter. Security, decentralization, and resilience to attacks seemed more important. But as crypto moved beyond experiments, it became clear: a slow blockchain cannot be mass-market.",
      "This is where Solana turned speed from a \"nice bonus\" into a core architectural principle.",
      "Why speed is not just TPS.",
      "When people talk about blockchain speed, they most often mention TPS — transactions per second. But in real products users care about something else: confirmation time, execution predictability, and the absence of stalls under load.",
      "Solana was designed not as a chain of rare and expensive operations, but as a system capable of processing a stream of events — almost like an exchange engine or a high-load API.",
      "In essence, Solana aims to be not just a blockchain, but real-time execution.",
      "Proof of History: the foundation of the millisecond race.",
      "Solana's key technical decision was Proof of History (PoH). Its idea is simple but radical: the network knows the order of events in advance, without spending time on constant coordination between nodes.",
      "This removes one of the most expensive elements of classic blockchains — time and sequence synchronization.",
      "As a result, validators operate faster, block confirmation is more stable, and the system scales better under growing load.",
      "PoH is not about \"more TPS\" — it's about less delay at every stage.",
      "Speed as a competitive weapon.",
      "Solana's high speed became not just a technological achievement, but a market factor. Thanks to it, the ecosystem gained: on-chain order books, high-frequency strategies, instant copy trading, prediction markets with live liquidity, and meme markets where entry/exit speed matters.",
      "On slow networks such products are either impossible or become simulations with off-chain logic.",
      "Solana showed that Web3 UX can be comparable to Web2 — and that changed user expectations.",
      "The downside of speed.",
      "It's important to understand: high speed always means trade-offs. Solana has faced network congestion, validator outages, and issues during extreme activity spikes.",
      "Each incident immediately becomes an argument for critics. But strategically, it is clear: Solana chose the path of complex engineering rather than safe minimalism.",
      "It scales not by limiting usage, but by constantly increasing infrastructure complexity.",
      "Firedancer and the next stage of the race.",
      "Perhaps the most important signal of Solana's maturity is the emergence of alternative client implementations. The Firedancer project, developed by Jump Crypto, is an attempt to rebuild the Solana validator from scratch to make it faster, more stable, and more resilient under load.",
      "This is a crucial point: speed stops being a \"single-client feature\" and becomes a system property.",
      "The millisecond race moves to the next level.",
      "Why this battle matters for the future.",
      "Speed in Solana is not about records and slide-deck numbers. It is about the kinds of markets that can exist: real-time trading, mass consumer apps, the creator economy, and prediction markets with instant reaction to events.",
      "The faster the network, the fewer reasons to move logic off-chain. That means more transparency, less trust, and a more real on-chain economy.",
      "Conclusion.",
      "Solana is not just in a blockchain race. It is in a race for the right to be real-time infrastructure.",
      "Yes, it is a risky path. Yes, it requires complex engineering. But it is this path that opens the door for new markets that were previously impossible in blockchain.",
    ],
    bullets: [
      "Скорость — это про латентность и предсказуемость, а не только TPS",
      "PoH снижает задержки и делает масштабирование стабильнее",
      "Быстрая сеть открывает рынки real-time и ончейн-экономику",
    ],
    bulletsEn: [
      "Speed is about latency and predictability, not only TPS",
      "PoH reduces delays and stabilizes scaling",
      "Fast networks enable real-time markets and on-chain economy",
    ],
  },
  {
    slug: "budushchee-za-creatorami-tokenov",
    title: "Почему будущее за креаторами токенов и как проекты поощряют их",
    titleEn: "Why the future belongs to token creators and how projects incentivize them",
    excerpt:
      "Фокус Web3 смещается от инфраструктуры к людям, которые создают внимание и приводят пользователей — креаторам.",
    excerptEn:
      "Web3 focus shifts from infrastructure to the people who create attention and bring users — creators.",
    category: "tech",
    date: "3 фев 2025",
    dateEn: "Feb 3, 2025",
    readTime: "8 мин",
    readTimeEn: "8 min",
    authorId: "israelyan",
    tags: ["creators", "tokenomics", "community", "web3"],
    image: "/blog/budushchee-za-creatorami-tokenov.jpg",
    body: [
      "Крипторынок долгое время развивался вокруг инфраструктуры: протоколы, блокчейны, L1 и L2, технические апгрейды. Но по мере взросления экосистемы фокус начал смещаться. Сегодня ключевой вопрос звучит иначе: кто создает ценность и кто приводит пользователей. Ответ всё чаще один — креаторы.",
      "От разработчиков к креаторам.",
      "Раньше запуск токена был прерогативой команд с серьезными ресурсами: разработка смарт-контрактов, аудит, маркетинг, листинги. Это создавало высокий порог входа и ограничивало эксперименты.",
      "Современные экосистемы, особенно Solana, этот порог резко снизили. Сегодня креатором токена может быть: комьюнити-лидер, трейдер с репутацией, медийная персона, нишевой инфлюенсер, даже анонимный пользователь с идеей и таймингом. Важно не кто ты, а можешь ли ты создать внимание и ликвидность.",
      "Токен как формат контента.",
      "Один из ключевых сдвигов последних лет — токен перестал быть исключительно финансовым инструментом. Он стал формой контента. Как пост, видео или стрим, токен быстро создаётся, быстро распространяется, живёт за счёт внимания и умирает без него.",
      "Это радикально меняет логику рынка. Ценность всё чаще формируется не из utility, а из нарратива, вовлечённости, комьюнити, способности удерживать интерес.",
      "Креаторы, которые понимают механику внимания, оказываются в выигрышной позиции.",
      "Почему проекты заинтересованы в креаторах.",
      "Для экосистем и платформ креаторы токенов — это не «шум», а двигатель роста. Каждый новый токен привлекает пользователей, создаёт транзакции, генерирует комиссии, увеличивает активность сети.",
      "По сути, креаторы становятся децентрализованным маркетингом, который масштабируется органически. Поэтому проекты начинают упрощать запуск токенов, снижать комиссии, внедрять реферальные и creator-программы, поощрять раннюю активность и объем. Это не альтруизм — это экономика.",
      "Стимулы как основа новой модели.",
      "В Web3 почти всё строится на стимулах. Если в Web2 креаторы зависят от платформ, то в Web3 они получают прямую финансовую связь с результатом.",
      "Удачный токен = рост цены → рост ликвидности → рост влияния креатора. При этом нет посредников, нет сложных контрактов, нет долгих согласований. Рынок сам оценивает идею в режиме реального времени.",
      "Почему это не пузырь, а эволюция.",
      "Критики часто называют creator-токены «мемами без смысла». Но это поверхностный взгляд. На самом деле рынок проходит знакомый путь: сначала — хаос и переизбыток, затем — фильтрация, потом — формирование устойчивых форматов.",
      "Ровно так же развивались YouTube, Instagram, NFT-рынок, DeFi. Большинство проектов исчезает, но инфраструктура и модели остаются.",
      "Роль Solana в этой трансформации.",
      "Solana стала идеальной средой для creator-экономики: низкие комиссии позволяют экспериментировать, высокая скорость делает рынок живым, простота UX снижает барьер входа.",
      "Здесь можно запускать токены не как «продукты на годы», а как гипотезы, проверяемые рынком за дни и часы. Именно поэтому creator-рынок на Solana развивается быстрее, чем где-либо ещё.",
      "Итог.",
      "Будущее Web3 — не только за протоколами и фондами. Оно за теми, кто умеет работать с вниманием, понимает динамику комьюнити, способен быстро запускать и адаптироваться.",
      "Креаторы токенов — это новая категория предпринимателей, маркетологов и продукт-менеджеров одновременно. И экосистемы, которые первыми научатся правильно поощрять и масштабировать их, получат решающее преимущество.",
    ],
    bodyEn: [
      "For a long time the crypto market evolved around infrastructure: protocols, blockchains, L1 and L2, technical upgrades. But as the ecosystem matured, the focus began to shift. Today the key question is different: who creates value and who brings users. The answer is increasingly one — creators.",
      "From developers to creators.",
      "Previously, launching a token was the privilege of teams with serious resources: smart contract development, audits, marketing, listings. That created a high entry barrier and limited experimentation.",
      "Modern ecosystems, especially Solana, drastically lowered that barrier. Today a token creator can be a community leader, a trader with reputation, a media personality, a niche influencer, or even an anonymous user with an idea and timing. What matters is not who you are, but whether you can create attention and liquidity.",
      "Token as a content format.",
      "One of the key shifts of recent years is that a token stopped being purely a financial instrument. It became a form of content. Like a post, a video, or a stream, a token is created quickly, spreads quickly, lives on attention, and dies without it.",
      "This radically changes market logic. Value is increasingly formed not from utility, but from narrative, engagement, community, and the ability to sustain interest.",
      "Creators who understand attention mechanics end up in a winning position.",
      "Why projects care about creators.",
      "For ecosystems and platforms, token creators are not \"noise\" — they are the engine of growth. Every new token attracts users, creates transactions, generates fees, and increases network activity.",
      "In essence, creators become decentralized marketing that scales organically. That is why projects simplify token launches, reduce fees, implement referral and creator programs, and reward early activity and volume. This is not altruism — it is economics.",
      "Incentives as the foundation of a new model.",
      "In Web3 almost everything is built on incentives. If in Web2 creators depend on platforms, in Web3 they get a direct financial link to outcomes.",
      "A successful token = price growth → liquidity growth → creator influence growth. There are no intermediaries, no complex contracts, no long approvals. The market evaluates the idea in real time.",
      "Why this is not a bubble but evolution.",
      "Critics often call creator tokens \"memes without meaning.\" But that is a superficial view. In reality the market follows a familiar path: first chaos and oversupply, then filtering, then the formation of stable formats.",
      "The same happened with YouTube, Instagram, the NFT market, and DeFi. Most projects disappear, but the infrastructure and models remain.",
      "Solana's role in this transformation.",
      "Solana has become an ideal environment for the creator economy: low fees enable experimentation, high speed keeps the market live, and simple UX lowers the barrier to entry.",
      "Here you can launch tokens not as \"products for years,\" but as hypotheses tested by the market in days and hours. That is why the creator market on Solana grows faster than anywhere else.",
      "Conclusion.",
      "The future of Web3 is not only about protocols and funds. It belongs to those who can work with attention, understand community dynamics, and ship quickly and adapt.",
      "Token creators are a new category of entrepreneurs, marketers, and product managers at once. Ecosystems that learn to incentivize and scale them first will gain a decisive advantage.",
    ],
    bullets: [
      "Креаторы становятся основным драйвером роста экосистем",
      "Токен превращается в формат контента и внимания",
      "Инфраструктура и стимулы определяют масштаб creator-рынка",
    ],
    bulletsEn: [
      "Creators become the main growth drivers for ecosystems",
      "Tokens turn into a format of content and attention",
      "Infrastructure and incentives define the scale of the creator market",
    ],
  },
  {
    slug: "tendencii-mem-rynka",
    title: "Тенденции мем-рынка",
    titleEn: "Meme market trends",
    excerpt:
      "Мем-рынок — это лаборатория внимания, где скорость реакции важнее фундаментала.",
    excerptEn:
      "The meme market is a laboratory of attention where reaction speed matters more than fundamentals.",
    category: "market",
    date: "10 фев 2025",
    dateEn: "Feb 10, 2025",
    readTime: "7 мин",
    readTimeEn: "7 min",
    authorId: "israelyan",
    tags: ["mem", "liquidity", "attention", "market"],
    image: "/blog/tendencii-mem-rynka.jpg",
    body: [
      "Мем-рынок часто воспринимают как хаос, но он демонстрирует точный срез поведения капитала и внимания. Здесь цена реагирует не на фундаментал, а на скорость распространения нарратива.",
      "Циклы становятся короче: то, что раньше жило неделями, теперь живет часами. Это меняет структуру ликвидности и требует другого подхода к стратегиям.",
      "Основной фактор успеха — реакция. Побеждает не тот, кто прав, а тот, кто быстрее фиксирует изменения и умеет закрываться без задержек.",
      "В таких условиях инфраструктура превращается в инструмент прибыли. Если стек не выдерживает пиков, стратегия перестает работать.",
      "Мем-рынок также показывает, как работает социальное доказательство: скорость распространения информации напрямую влияет на цену.",
      "Для продуктов это урок — скорость UX и исполнение сделок становятся критичными. Любая задержка воспринимается как дефект.",
      "Рост мем-рынка подталкивает к появлению специализированных инструментов: сканеров, сигналов, автоматизации входов и выходов.",
      "Этот сегмент будет оставаться волатильным, но именно поэтому он остается отличным стресс-тестом для инфраструктуры.",
    ],
    bodyEn: [
      "The meme market is often perceived as chaos, but it reveals a precise snapshot of capital and attention behavior. Price reacts not to fundamentals, but to the speed of narrative spread.",
      "Cycles are shorter: what used to live for weeks now lives for hours. This changes liquidity structure and requires a different approach to strategies.",
      "The key factor is reaction. The winner is not the one who is right, but the one who reacts faster and can close positions without delay.",
      "In these conditions infrastructure becomes a profit tool. If the stack cannot handle spikes, the strategy stops working.",
      "The meme market also shows how social proof works: the speed of information spread directly affects price.",
      "For products this is a lesson — UX speed and trade execution are critical. Any delay is perceived as a defect.",
      "The growth of meme markets pushes the creation of specialized tools: scanners, signals, and automated entries and exits.",
      "This segment will remain volatile, but that is why it is an excellent stress test for infrastructure.",
    ],
    bullets: [
      "Внимание становится новой ликвидностью",
      "Скорость реакции определяет результат",
      "Инфраструктура — часть торговой стратегии",
    ],
    bulletsEn: [
      "Attention becomes the new liquidity",
      "Reaction speed determines the outcome",
      "Infrastructure is part of the trading strategy",
    ],
  },
  {
    slug: "prediction-market-pylesosit-rynok",
    title: "Предикшн-маркеты «пылесосят» рынок: почему ликвидность уходит туда",
    titleEn: "Prediction markets vacuum the market: why liquidity flows there",
    excerpt:
      "Ликвидность перетекает туда, где проще и честнее выражать мнение деньгами — и предикшн-маркеты стали таким центром притяжения.",
    excerptEn:
      "Liquidity flows to where it is easier and more honest to express an opinion with money — and prediction markets became that center of gravity.",
    category: "market",
    date: "18 фев 2025",
    dateEn: "Feb 18, 2025",
    readTime: "8 мин",
    readTimeEn: "8 min",
    authorId: "israelyan",
    tags: ["prediction markets", "liquidity", "trading"],
    image: "/blog/prediction-market-pylesosit-rynok.jpg",
    body: [
      "В криптоиндустрии ликвидность всегда перетекает туда, где проще, быстрее и честнее выражать мнение деньгами. За последние годы именно предикшн-маркеты стали одной из таких точек притяжения. Они не просто растут — они буквально высасывают активность из других сегментов рынка.",
      "Причина проста: prediction markets совпали с тем, как сегодня думает трейдер.",
      "От «мнений» к ставкам.",
      "Классический трейдинг строится вокруг интерпретаций: новостей, графиков, макроэкономики, инсайдов.",
      "Предикшн-маркет упрощает всё до одного вопроса: произойдёт событие или нет? Без сложных деривативов, плечей и терминологии. Ты либо прав, либо нет. Именно эта бинарность делает формат таким привлекательным.",
      "Почему ликвидность уходит именно сюда.",
      "Предикшн-маркеты выигрывают сразу по нескольким направлениям: низкий когнитивный порог, понятная логика входа и выхода, короткий горизонт сделок, прямое соответствие между событием и результатом.",
      "Трейдеру больше не нужно «доказывать рынку», что он умнее графика. Достаточно правильно оценить вероятность.",
      "Это особенно хорошо ложится на текущий рынок, где новости сменяются быстро, внимание фрагментировано, долгосрочная уверенность редка.",
      "Эффект «пылесоса».",
      "Prediction markets начинают выполнять роль агрегатора ожиданий. Туда стекаются политические прогнозы, экономические ожидания, спортивные события, технологические релизы. Каждый такой рынок — это мини-биржа с собственной ликвидностью. И чем больше событий, тем сильнее эффект масштаба.",
      "В какой-то момент трейдеру проще поставить на исход события, чем покупать токен, ждать реакции рынка, бороться с волатильностью.",
      "Роль Solana в росте формата.",
      "Быстрые сети вроде Solana сделали prediction markets практически «реальным временем». Когда ордера исполняются мгновенно, комиссии минимальны, интерфейс не тормозит, рынок начинает вести себя как классический трейдинг, но без лишних слоёв.",
      "Это критично: предикшн-маркеты умирают там, где есть задержка.",
      "Почему это угроза другим сегментам.",
      "Каждый доллар, зашедший в prediction market, — это доллар, который не пошёл в спотовый трейдинг, в мем-рынок, в классические DeFi-протоколы.",
      "Предикшн-маркеты конкурируют не за капитал, а за внимание и активность. А в Web3 это главный ресурс.",
      "Итог.",
      "Prediction markets растут не потому, что это «модно». Они растут потому, что идеально соответствуют мышлению трейдера, скорости новостного цикла, желанию быстро выразить мнение деньгами.",
      "И пока рынок становится всё более событийным, этот формат будет пылесосить ликвидность дальше.",
    ],
    bodyEn: [
      "In crypto, liquidity always flows to where it is easier, faster, and more honest to express an opinion with money. Over the last few years, prediction markets have become one of those attraction points. They do not just grow — they literally pull activity out of other market segments.",
      "The reason is simple: prediction markets match how traders think today.",
      "From \"opinions\" to bets.",
      "Classic trading is built on interpretations: news, charts, macroeconomics, insiders.",
      "A prediction market simplifies everything to one question: will the event happen or not? No complex derivatives, leverage, or terminology. You are either right or wrong. This binary nature is what makes the format so attractive.",
      "Why liquidity flows here.",
      "Prediction markets win on several fronts: low cognitive load, clear entry/exit logic, short trade horizons, and direct correspondence between event and outcome.",
      "A trader no longer needs to \"prove to the market\" that they are smarter than the chart. It is enough to assess probability correctly.",
      "This fits the current market where news cycles are fast, attention is fragmented, and long-term conviction is rare.",
      "The \"vacuum\" effect.",
      "Prediction markets start acting as an aggregator of expectations. Political forecasts, economic expectations, sports events, and tech releases flow there. Each market is a mini-exchange with its own liquidity. The more events, the stronger the scale effect.",
      "At some point it becomes easier for a trader to bet on an event outcome than to buy a token, wait for market reaction, and fight volatility.",
      "Solana's role in the format's growth.",
      "Fast networks like Solana made prediction markets practically \"real time.\" When orders execute instantly, fees are minimal, and the interface does not lag, the market behaves like classic trading, but without extra layers.",
      "This is critical: prediction markets die where there is latency.",
      "Why this threatens other segments.",
      "Every dollar that goes into a prediction market is a dollar that did not go to spot trading, the meme market, or classic DeFi protocols.",
      "Prediction markets compete not for capital, but for attention and activity. And in Web3 that is the main resource.",
      "Conclusion.",
      "Prediction markets grow not because they are \"trendy.\" They grow because they perfectly fit trader thinking, the speed of the news cycle, and the desire to express an opinion quickly with money.",
      "And as the market becomes more event-driven, this format will keep vacuuming liquidity.",
    ],
    bullets: [
      "Предикшн-маркеты упрощают ставки до бинарных решений",
      "Формат забирает внимание и ликвидность у других сегментов",
      "Скорость сетей делает prediction markets конкурентным ядром",
    ],
    bulletsEn: [
      "Prediction markets simplify bets to binary decisions",
      "The format pulls attention and liquidity from other segments",
      "Network speed makes prediction markets a competitive core",
    ],
  },
  {
    slug: "problema-centralizacii-prediction-marketov",
    title:
      "Проблема централизации предикшн-маркетов: главный риск растущего формата",
    titleEn:
      "The centralization problem in prediction markets: the main risk of a growing format",
    excerpt:
      "По мере роста prediction markets их ключевая системная проблема проявляется все сильнее — централизация исходов.",
    excerptEn:
      "As prediction markets grow, their key systemic issue becomes more visible — centralized outcomes.",
    category: "market",
    date: "24 фев 2025",
    dateEn: "Feb 24, 2025",
    readTime: "9 мин",
    readTimeEn: "9 min",
    authorId: "beleken",
    tags: ["decentralization", "risk", "markets"],
    image: "/blog/problema-centralizacii-prediction-marketov.jpg",
    body: [
      "Предикшн-маркеты выглядят как один из самых честных и прозрачных форматов трейдинга: ставка на событие, понятный исход, рыночная цена вероятности. Но по мере роста этого сегмента всё отчетливее проявляется его системная проблема — централизация.",
      "Именно она может стать главным ограничителем дальнейшего развития формата.",
      "Где именно возникает централизация.",
      "На первый взгляд prediction market — децентрализованный продукт. Торговля происходит ончейн, ставки публичны, ликвидность прозрачна. Но ключевой элемент находится в другом месте — в определении исхода события.",
      "Каждый рынок упирается в вопросы: кто решает, что событие произошло? на основании каких данных? кто имеет право оспаривать результат?",
      "На практике ответы часто сводятся к: централизованным оракулам, ручной модерации, ограниченному кругу арбитров. Это создаёт точку контроля, несовместимую с идеей полностью децентрализованного рынка.",
      "Оракулы как слабое звено.",
      "Оракул — это мост между реальным миром и блокчейном. И именно он чаще всего становится бутылочным горлышком доверия.",
      "Если источник данных ограничен, процесс принятия решения непрозрачен, нет эффективного механизма апелляции, то рынок фактически превращается в ставку на решение оператора, а не на событие.",
      "Для трейдера это критично, потому что риск становится не рыночным, а административным, невозможно корректно оценить вероятность, доверие подменяет математику.",
      "Почему рынок это терпит.",
      "Парадоксально, но централизация долгое время не мешает росту. Причина проста: UX и ликвидность важнее идеологии.",
      "Пока исходы решаются быстро, деньги выплачиваются корректно, скандалы редки, большинство пользователей готовы закрывать глаза на архитектурные компромиссы. Но с ростом объемов цена ошибки становится выше.",
      "Централизация и цензура.",
      "Еще один риск — цензура рынков. Когда платформа решает, какие события можно торговать, какие темы запрещены, какие рынки закрываются, prediction market перестаёт быть отражением коллективного мнения и становится отфильтрованной витриной допустимых прогнозов.",
      "Это особенно чувствительно в политике, геополитике, макроэкономике. А именно эти темы привлекают наибольшую ликвидность.",
      "Почему децентрализация здесь сложнее, чем кажется.",
      "Полная децентрализация в prediction markets — нетривиальная задача: события часто неоднозначны, формулировки могут трактоваться по-разному, автоматизация не покрывает реальный мир на 100%.",
      "Поэтому рынок сейчас находится в компромиссной фазе: достаточно централизован, чтобы работать, и достаточно децентрализован, чтобы выглядеть честно. Но по мере взросления формата этот баланс станет всё менее устойчивым.",
      "Итог.",
      "Централизация — это не временный баг, а структурный вызов prediction markets. Именно от того, как индустрия решит вопрос оракулов, арбитража и управления исходами, будет зависеть, станет ли формат фундаментом Web3-трейдинга или останется нишевым инструментом.",
    ],
    bodyEn: [
      "Prediction markets look like one of the most honest and transparent trading formats: a bet on an event, a clear outcome, and a market price of probability. But as the segment grows, its systemic problem becomes increasingly apparent — centralization.",
      "It may become the main constraint on the format’s future growth.",
      "Where centralization actually appears.",
      "At first glance a prediction market is a decentralized product. Trading is on-chain, bets are public, liquidity is transparent. But the key element is elsewhere — in determining the outcome of the event.",
      "Every market runs into questions: who decides that the event happened? based on which data? who has the right to challenge the result?",
      "In practice the answers often boil down to centralized oracles, manual moderation, or a limited circle of arbiters. That creates a control point incompatible with the idea of a fully decentralized market.",
      "Oracles as the weakest link.",
      "An oracle is the bridge between the real world and the blockchain. And it most often becomes the bottleneck of trust.",
      "If the data source is limited, the decision process is opaque, and there is no effective appeal mechanism, the market effectively becomes a bet on the operator’s decision rather than the event itself.",
      "For a trader this is critical, because risk becomes administrative rather than market-based, probabilities cannot be assessed correctly, and trust replaces math.",
      "Why the market tolerates it.",
      "Paradoxically, centralization does not stop growth for a long time. The reason is simple: UX and liquidity outweigh ideology.",
      "As long as outcomes are resolved quickly, payouts are correct, and scandals are rare, most users are willing to overlook architectural compromises. But as volumes grow, the cost of error rises.",
      "Centralization and censorship.",
      "Another risk is market censorship. When a platform decides which events can be traded, which topics are banned, and which markets are closed, a prediction market stops reflecting collective opinion and becomes a filtered showcase of acceptable forecasts.",
      "This is especially sensitive in politics, geopolitics, and macroeconomics — and those topics attract the most liquidity.",
      "Why decentralization here is harder than it seems.",
      "Full decentralization in prediction markets is not trivial: events are often ambiguous, wording can be interpreted differently, and automation does not cover the real world 100%.",
      "So the market sits in a compromise phase: centralized enough to work, decentralized enough to look honest. But as the format matures, this balance will become less stable.",
      "Conclusion.",
      "Centralization is not a temporary bug, but a structural challenge for prediction markets. Whether the industry can solve oracles, arbitration, and outcome governance will determine if the format becomes the foundation of Web3 trading or remains a niche tool.",
    ],
    bullets: [
      "Централизованные оракулы создают точку контроля",
      "UX и ликвидность пока перевешивают идеологию",
      "Без прозрачного арбитража доверие рушится",
    ],
    bulletsEn: [
      "Centralized oracles create a control point",
      "UX and liquidity still outweigh ideology",
      "Without transparent arbitration, trust collapses",
    ],
  },
  {
    slug: "kto-stoit-za-polymarket",
    title: "Кто стоит за Polymarket и почему его активно продвигают",
    titleEn: "Who is behind Polymarket and why it is promoted so actively",
    excerpt:
      "Polymarket стал флагманом prediction‑сегмента за счет сильного продукта, капитала и удачного тайминга.",
    excerptEn:
      "Polymarket became the flagship of the prediction segment thanks to a strong product, capital, and good timing.",
    category: "market",
    date: "3 мар 2025",
    dateEn: "Mar 3, 2025",
    readTime: "8 мин",
    readTimeEn: "8 min",
    authorId: "beleken",
    tags: ["polymarket", "growth", "market"],
    image: "/blog/kto-stoit-za-polymarket.jpg",
    body: [
      "Рост prediction markets сложно обсуждать, не упоминая Polymarket. За короткое время платформа превратилась из нишевого продукта в флагмана всего сегмента. И это не случайность.",
      "Polymarket как продукт, а не эксперимент.",
      "В отличие от многих Web3-проектов, Polymarket с самого начала строился как consumer-friendly продукт, с понятным интерфейсом, минимальным порогом входа и фокусом на реальные события.",
      "Здесь нет ощущения «криптосервиса для своих». Это важно: рынок растёт только тогда, когда им могут пользоваться не только энтузиасты.",
      "Кто стоит за ростом.",
      "За Polymarket стоит сочетание сильной продуктовой команды, поддержки венчурного капитала и удачного тайминга.",
      "Проект оказался в точке, где сошлись усталость от сложного DeFi, рост интереса к событиям и новостям, желание торговать без плеч и ликвидаций.",
      "Polymarket предложил простую форму выражения мнения деньгами — и рынок откликнулся.",
      "Почему его активно продвигают.",
      "Продвижение Polymarket — это не только маркетинг. Платформа решает сразу несколько задач для экосистемы: привлекает новую аудиторию, увеличивает ончейн-активность, формирует новый класс трейдеров.",
      "Prediction markets хорошо вписываются в нарратив «умных денег», аналитики и коллективного прогнозирования. Это делает их удобным объектом для медиа и инфлюенсеров.",
      "Эффект сетевого роста.",
      "Чем больше пользователей на Polymarket, тем точнее цены, тем выше ликвидность, тем сильнее доверие к рынку.",
      "Возникает классический network effect. И на этом этапе догонять лидера становится крайне сложно.",
      "Итог.",
      "Polymarket — это не просто платформа. Это точка сборки формата, вокруг которой сейчас выстраивается весь рынок prediction markets.",
    ],
    bodyEn: [
      "It is hard to discuss the rise of prediction markets without mentioning Polymarket. In a short time the platform went from a niche product to the flagship of the whole segment — and that is not accidental.",
      "Polymarket as a product, not an experiment.",
      "Unlike many Web3 projects, Polymarket was built from the start as a consumer-friendly product, with a clear interface, low entry barrier, and focus on real events.",
      "There is no feeling of a \"crypto service for insiders.\" This matters: the market only grows when it can be used by more than enthusiasts.",
      "Who is behind the growth.",
      "Polymarket sits at the intersection of a strong product team, venture capital backing, and good timing.",
      "The project appeared where fatigue from complex DeFi, rising interest in events and news, and the desire to trade without leverage and liquidations all converged.",
      "Polymarket offered a simple way to express opinions with money — and the market responded.",
      "Why it is promoted so actively.",
      "Promotion of Polymarket is not just marketing. The platform solves several ecosystem tasks: it attracts a new audience, increases on-chain activity, and forms a new class of traders.",
      "Prediction markets fit the narrative of \"smart money,\" analytics, and collective forecasting. That makes them a convenient target for media and influencers.",
      "The network effect.",
      "The more users on Polymarket, the more accurate the prices, the higher the liquidity, and the stronger the trust in the market.",
      "A classic network effect emerges. At this stage it becomes extremely hard to catch up to the leader.",
      "Conclusion.",
      "Polymarket is not just a platform. It is the coordination point of the format, around which the entire prediction markets landscape is being built.",
    ],
    bullets: [
      "Сильный продукт делает рынок массовым",
      "Капитал и тайминг усиливают рост",
      "Сетевой эффект закрепляет лидерство",
    ],
    bulletsEn: [
      "A strong product makes the market mass",
      "Capital and timing amplify growth",
      "Network effects lock in leadership",
    ],
  },
  {
    slug: "polymarket-novyi-glotok-vozduha",
    title: "Polymarket — новый глоток воздуха для трейдеров",
    titleEn: "Polymarket — a breath of fresh air for traders",
    excerpt:
      "Polymarket стал альтернативой классическому криптотрейдингу — проще, чище и честнее по логике.",
    excerptEn:
      "Polymarket became an alternative to classic crypto trading — simpler, cleaner, and more honest by design.",
    category: "market",
    date: "10 мар 2025",
    dateEn: "Mar 10, 2025",
    readTime: "7 мин",
    readTimeEn: "7 min",
    authorId: "israelyan",
    tags: ["polymarket", "trading", "hedge"],
    image: "/blog/polymarket-novyi-glotok-vozduha.jpg",
    body: [
      "Для многих трейдеров Polymarket стал альтернативой классическому криптотрейдингу. Не потому что он «выгоднее», а потому что он проще и честнее по своей логике.",
      "Усталость от классического трейдинга.",
      "Современный криптотрейдинг — это шум, сложные деривативы, охота за ликвидациями, постоянная неопределенность.",
      "Prediction market убирает лишнее. Остаётся только вопрос и вероятность.",
      "Торговля смыслом, а не шумом.",
      "На Polymarket трейдер торгует ожидания, события, консенсус. Это ближе к аналитике и мышлению, чем к борьбе с ботами и HFT.",
      "Важно не скорость реакции, а качество оценки вероятности.",
      "Почему формат зашел.",
      "Polymarket дал трейдерам короткий горизонт, понятный риск, прозрачный результат.",
      "Ты заранее знаешь: сколько можешь потерять, при каком исходе заработаешь, когда рынок закроется. Это редкость в крипте.",
      "Новый тип трейдера.",
      "Prediction markets формируют новый профиль участника: менее эмоциональный, более аналитичный, ориентированный на события, а не графики.",
      "Это меняет саму культуру трейдинга.",
      "Итог.",
      "Polymarket стал «глотком воздуха» не потому, что он идеален. А потому, что он показал: трейдинг может быть проще, чище и ближе к реальности.",
      "И именно поэтому prediction markets — не временный тренд, а устойчивое направление развития рынка.",
    ],
    bodyEn: [
      "For many traders Polymarket became an alternative to classic crypto trading. Not because it is \"more profitable,\" but because it is simpler and more honest in its logic.",
      "Fatigue from classic trading.",
      "Modern crypto trading is noise, complex derivatives, liquidation hunting, and constant uncertainty.",
      "Prediction markets remove the excess. Only the question and the probability remain.",
      "Trading meaning, not noise.",
      "On Polymarket a trader trades expectations, events, and consensus. It is closer to analysis and reasoning than to fighting bots and HFT.",
      "What matters is not reaction speed, but the quality of probability assessment.",
      "Why the format clicked.",
      "Polymarket gave traders short horizons, clear risk, and transparent outcomes.",
      "You know in advance how much you can lose, under which outcome you win, and when the market closes. That is rare in crypto.",
      "A new type of trader.",
      "Prediction markets form a new participant profile: less emotional, more analytical, and oriented around events rather than charts.",
      "This changes the culture of trading itself.",
      "Conclusion.",
      "Polymarket became a \"breath of fresh air\" not because it is perfect, but because it showed that trading can be simpler, cleaner, and closer to reality.",
      "That is why prediction markets are not a temporary trend but a sustainable direction for market development.",
    ],
    bullets: [
      "Prediction markets упрощают трейдинг до оценки вероятности",
      "Прозрачные риски снижают эмоциональность",
      "Формат формирует новый тип трейдеров",
    ],
    bulletsEn: [
      "Prediction markets reduce trading to probability assessment",
      "Transparent risks lower emotional trading",
      "The format forms a new type of trader",
    ],
  },
];

export const postSummaries: PostSummary[] = posts.map(
  ({ body, bullets, bodyEn, bulletsEn, ...summary }) => summary,
);

export const postsBySlug = Object.fromEntries(
  posts.map((post) => [post.slug, post] as const),
) as Record<string, Post>;

export const getAuthorById = (id: string) =>
  authors.find((author) => author.id === id);
